import { NextResponse } from "next/server";

export async function GET() {
  const declared = {
    NEXT_SHOPIFY_ACCESS_TOKEN: process.env.NEXT_SHOPIFY_ACCESS_TOKEN,
    NEXT_SHOPIFY_API_KEY: process.env.NEXT_SHOPIFY_API_KEY,
    NEXT_SHOPIFY_SECRET_KEY: process.env.NEXT_SHOPIFY_SECRET_KEY,
    NEXT_SHOPIFY_STORE_DOMAIN: process.env.NEXT_SHOPIFY_STORE_DOMAIN,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:
      process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
    NEXT_PUBLIC_STRIPE_SUCCESS_URL: process.env.NEXT_PUBLIC_STRIPE_SUCCESS_URL,
    NEXT_PUBLIC_BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
    NEXT_PUBLIC_CANCEL_URL: process.env.NEXT_PUBLIC_CANCEL_URL,
    PAYPAL_CLIENT_ID: process.env.PAYPAL_CLIENT_ID,
    PAYPAL_SECRET: process.env.PAYPAL_SECRET,
  };

  const used = {
    NEXT_SHOPIFY_ACCESS_TOKEN: process.env.NEXT_SHOPIFY_ACCESS_TOKEN,
    NEXT_SHOPIFY_STORE_DOMAIN: process.env.NEXT_SHOPIFY_STORE_DOMAIN,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    NEXT_PUBLIC_STRIPE_SUCCESS_URL: process.env.NEXT_PUBLIC_STRIPE_SUCCESS_URL,
    NEXT_PUBLIC_BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
    NEXT_PUBLIC_CANCEL_URL: process.env.NEXT_PUBLIC_CANCEL_URL,
    PAYPAL_CLIENT_ID: process.env.PAYPAL_CLIENT_ID,
    PAYPAL_SECRET: process.env.PAYPAL_SECRET,
    NEXT_PUBLIC_STORE_URL: process.env.NEXT_PUBLIC_STORE_URL,
  };

  return NextResponse.json({
    declared,
    used,
  });
}
